# Site settings
title: RAPPY SAHA
email: rappysaha10@gmail.com
description: "Homepage of Rappy Saha"
baseurl: ""
url: "https://rappysaha.github.io"
github_username:  rappysaha

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Number of news stories on the front page.
front_page_news: 10

gems:
  - jekyll-sitemap

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Jekyll theme inspired by researcher"


sass:
    style: compressed
    sass_dir: _sass